"""
Local settings for project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import os

from . import common


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = common.BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = common.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

INTERNAL_IPS = '127.0.0.1'

# Application definition

INSTALLED_APPS = [
    # Django Debug Toolbar
    'debug_toolbar',
]
INSTALLED_APPS += common.INSTALLED_APPS

MIDDLEWARE = [
    # Django Debug Toolbar
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]
MIDDLEWARE += common.MIDDLEWARE

# Django Debug Toolbar
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
]

# ROOT_URLCONF = 'config.urls'
ROOT_URLCONF = common.ROOT_URLCONF

TEMPLATES = common.TEMPLATES

WSGI_APPLICATION = common.WSGI_APPLICATION


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = common.AUTH_PASSWORD_VALIDATORS


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = common.LANGUAGE_CODE

TIME_ZONE = common.TIME_ZONE

USE_I18N = common.USE_I18N

USE_L10N = common.USE_L10N

USE_TZ = common.USE_TZ


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = common.STATIC_URL

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
